import React, { useState } from 'react';
import {
  Send,
  Plus,
  RotateCcw,
  Search,
  Eye
} from 'lucide-react';

interface ClientRequestsViewProps {
  onOpenCreateRequest: () => void;
  onOpenMatter: (matterId: string) => void;
}

export const ClientRequestsView: React.FC<ClientRequestsViewProps> = ({
  onOpenCreateRequest,
  onOpenMatter,
}) => {
  const [searchQuery, setSearchQuery] = useState('');
  const [typeFilter, setTypeFilter] = useState('All');
  const [selectedReq, setSelectedReq] = useState<any | null>(null);

  const requests = [
    { id: 'REQ-101', title: 'Q3 2026 Matter Summary', type: 'Matter Summary', matterId: 'MAT-301', date: '24 Sep 2026', by: 'Legal Team', status: 'Completed', detail: 'Requested executive summary of FY26 restructuring tax points.' },
    { id: 'REQ-102', title: 'Tax Compliance Report', type: 'Compliance', matterId: 'MAT-301', date: '15 Sep 2026', by: 'Legal Team', status: 'In Progress', detail: 'Requested GST audit report and tax compliance certificate.' },
    { id: 'REQ-103', title: 'Case Progress Report', type: 'Progress', matterId: 'MAT-178', date: '10 Sep 2026', by: 'Legal Team', status: 'Completed', detail: 'Requested status update on High Court Writ petition hearing.' },
  ];

  const filteredRequests = requests.filter((r) => {
    const matchesSearch = r.title.toLowerCase().includes(searchQuery.toLowerCase()) || r.matterId.toLowerCase().includes(searchQuery.toLowerCase());
    const matchesType = typeFilter === 'All' || r.type === typeFilter;
    return matchesSearch && matchesType;
  });

  return (
    <div className="space-y-6 max-w-6xl mx-auto">
      {/* Header Banner */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-3 border-b border-white/10">
        <div>
          <h1 className="text-2xl font-extrabold text-white tracking-tight flex items-center gap-2">
            <Send className="w-6 h-6 text-[#00B8FF]" />
            <span>My Requests ({requests.length})</span>
          </h1>
          <p className="text-xs text-slate-400 mt-1">
            Create and track requests raised by the client.
          </p>
        </div>
        <button
          onClick={onOpenCreateRequest}
          className="px-4 py-2 rounded-xl bg-[#00B8FF] hover:bg-[#0098D4] text-white font-bold text-xs flex items-center gap-2 transition-all cursor-pointer shadow-lg shadow-sky-500/20"
        >
          <Plus className="w-4 h-4" />
          <span>Create Request</span>
        </button>
      </div>

      {/* Filter Bar (Ref Panel 7) */}
      <div className="p-4 rounded-2xl bg-[#081525] border border-white/10 flex flex-wrap items-center justify-between gap-3">
        <div className="flex-1 min-w-[240px] relative">
          <input
            type="text"
            placeholder="Search requests..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="w-full pl-9 pr-4 py-2 rounded-xl bg-[#041828] border border-white/10 text-xs text-white placeholder-slate-500 focus:outline-none focus:border-[#00B8FF]"
          />
          <Search className="w-4 h-4 text-slate-400 absolute left-3 top-2.5" />
        </div>

        <div className="flex flex-wrap items-center gap-2">
          <select
            value={typeFilter}
            onChange={(e) => setTypeFilter(e.target.value)}
            className="px-3 py-2 rounded-xl bg-[#041828] border border-white/10 text-xs text-slate-300 font-medium focus:outline-none focus:border-[#00B8FF]"
          >
            <option value="All">All Types</option>
            <option value="Matter Summary">Matter Summary</option>
            <option value="Compliance">Compliance</option>
            <option value="Progress">Progress</option>
          </select>

          <button
            onClick={() => {
              setSearchQuery('');
              setTypeFilter('All');
            }}
            className="p-2 rounded-xl bg-white/5 hover:bg-white/10 text-slate-400 hover:text-white border border-white/10 transition-all cursor-pointer"
            title="Reset Filters"
          >
            <RotateCcw className="w-4 h-4" />
          </button>
        </div>
      </div>

      {/* Requests Table (Ref Panel 7) */}
      <div className="p-6 rounded-2xl bg-[#081525] border border-white/10 space-y-4">
        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs">
            <thead className="bg-[#041828] text-slate-400 uppercase font-mono text-[10px]">
              <tr>
                <th className="p-3.5 rounded-l-lg">Request Name</th>
                <th className="p-3.5">Type</th>
                <th className="p-3.5">Matter</th>
                <th className="p-3.5">Generated Date</th>
                <th className="p-3.5">Generated By</th>
                <th className="p-3.5 text-right rounded-r-lg">Action</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-white/5">
              {filteredRequests.map((req) => (
                <tr key={req.id} className="hover:bg-white/[0.02]">
                  <td className="p-3.5 font-bold text-white max-w-[220px] truncate">{req.title}</td>
                  <td className="p-3.5 text-slate-300 font-medium">{req.type}</td>
                  <td className="p-3.5">
                    <button
                      onClick={() => onOpenMatter(req.matterId)}
                      className="font-mono text-xs font-bold text-[#00B8FF] hover:underline cursor-pointer"
                    >
                      {req.matterId}
                    </button>
                  </td>
                  <td className="p-3.5 font-mono text-slate-400">{req.date}</td>
                  <td className="p-3.5 text-slate-400">{req.by}</td>
                  <td className="p-3.5 text-right">
                    <button
                      onClick={() => setSelectedReq(req)}
                      className="px-3 py-1.5 rounded-lg bg-[#00B8FF]/10 hover:bg-[#00B8FF]/20 text-[#00B8FF] border border-[#00B8FF]/30 font-bold text-xs flex items-center gap-1 ml-auto cursor-pointer"
                    >
                      <Eye className="w-3.5 h-3.5" />
                      <span>View</span>
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {/* Request Detail Modal */}
      {selectedReq && (
        <div className="fixed inset-0 bg-black/70 backdrop-blur-sm flex items-center justify-center p-4 z-50 animate-fadeIn">
          <div className="bg-[#081525] border border-[#00B8FF]/30 rounded-2xl p-6 max-w-md w-full space-y-4 shadow-2xl">
            <div className="flex items-center justify-between border-b border-white/10 pb-3">
              <h3 className="font-extrabold text-white text-base">{selectedReq.title}</h3>
              <span className="font-mono text-xs text-[#00B8FF] font-bold">{selectedReq.id}</span>
            </div>

            <div className="space-y-2 text-xs">
              <div>
                <span className="text-slate-400 block">Matter:</span>
                <span className="font-mono font-bold text-[#00B8FF]">{selectedReq.matterId}</span>
              </div>
              <div>
                <span className="text-slate-400 block">Type:</span>
                <span className="text-white font-semibold">{selectedReq.type}</span>
              </div>
              <div>
                <span className="text-slate-400 block">Created On:</span>
                <span className="font-mono text-slate-300">{selectedReq.date}</span>
              </div>
              <div>
                <span className="text-slate-400 block">Request Detail:</span>
                <p className="text-slate-200 mt-1 bg-[#041828] p-3 rounded-xl border border-white/5">{selectedReq.detail}</p>
              </div>
            </div>

            <div className="pt-2 flex justify-end">
              <button
                onClick={() => setSelectedReq(null)}
                className="px-4 py-2 rounded-xl bg-[#00B8FF] text-white font-bold text-xs cursor-pointer"
              >
                Close
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default ClientRequestsView;
